export const weatherIcons = new Map<number, string>();
weatherIcons.set(0, "☀️");
weatherIcons.set(1, "🌤️");
weatherIcons.set(2, "🌥️");
weatherIcons.set(3, "☁️");
weatherIcons.set(45, "🌫️");
weatherIcons.set(48, "❄️");
weatherIcons.set(51, "☁️🌧️☁️");
weatherIcons.set(53, "🌧️☁️");
weatherIcons.set(55, "🌧️");
weatherIcons.set(56, "❄️");
weatherIcons.set(57, "❄️❄️");
weatherIcons.set(61, "☁️🌧️☁️");
weatherIcons.set(63, "🌧️☁️");
weatherIcons.set(65, "🌧️");
weatherIcons.set(66, "❄️🌧️");
weatherIcons.set(67, "🌧️❄️🌧️");
weatherIcons.set(71, "🌨️");
weatherIcons.set(73, "🌨️🌨️");
weatherIcons.set(75, "🌨️🌨️🌨️");
weatherIcons.set(77, "❄️");
weatherIcons.set(80, "🌧️");
weatherIcons.set(81, "🌧️🌧️");
weatherIcons.set(82, "🌧️🌧️🌧️");
weatherIcons.set(85, "🌨️");
weatherIcons.set(86, "🌨️🌨️");
weatherIcons.set(95, "⛈️");
weatherIcons.set(96, "⛈️");
weatherIcons.set(99, "⛈️");

export const humanReadable = new Map<string, string>();
humanReadable.set("time", "Time");
humanReadable.set("temperature_2m", "T");
humanReadable.set("relativehumidity_2m", "RH");
humanReadable.set("precipitation_probability", "PoP");
humanReadable.set("precipitation", "H20");
humanReadable.set("weathercode", "Type");
humanReadable.set("windspeed_10m", "Wind");